### PR TITLE
dev/55: Add border to exam navbar

### LINKED ISSUE #55: Update navbar CSS in ExamPage
The CSS of navbar on the exam page has been updated. 
image

### PR DESCRIPTION
**Pull request by edisonhello**
Resolves #55.

image

### CODE REVIEW

**Review by Johnny850807 — APPROVED** [review]
ＬＧＴＭ

**Comment by Chaoyuuu** [comment]
1. Remove ScoreBoard and LiveSubmission tabs. We don't have these features in the current version.
2. Where is the exam name on the navbar?

**Review by Chaoyuuu — CHANGES_REQUESTED** [review]
Review Done !

**Comment by edisonhello** [comment]
@Chaoyuuu 
image

About the exam name, that is a good question.
Idk why it happens and don't know how to reproduce. I can fix it if we found a way to reproduce it.

**Review by Chaoyuuu — APPROVED** [review]
LGTM 😄

**Pull request merged**
